### ISSUE TITLE
What ffmpeg version to use? (Example of a working build environment?)

### ISSUE THREAD

**Issue by exrhizo** [Kitware/kwiver#1]
This isn't exactly a bug with your software, but it is not clear what the build environment should be.

I had compiled the latest version of ffmpeg for working with opencv but then that is not compatible with VXL.

Then I tried finding a version [suggested in this (probably too old) post](http://sourceforge.net/p/vxl/mailman/message/20620601/) but that revision -r11322 doesn't compile with your version of opencv from fletch.

Anyway, I just wanted to know what a working build environment is.

Thank you!!

Alex

**Comment by Cookt2** [comment]
Supported FFMPEG versions are 3.3.3 and 2.6.2. For ease of use, these versions are included as part of Kitware's [Fletch](https://github.com/Kitware/fletch). Closing...
