### ISSUE TITLE
class_map is "broken"

### ISSUE THREAD

**Issue by mwoehlke-kitware** [Kitware/kwiver#1049]
So, I see `detected_object_type` has been replaced by `class_map`. This is nice for code sharing, but unfortunately it has a fatal usability flaw; it is no longer possible to get the list of all known object types. (Signaling of added names is likely also broken.)

This needs to be refactored into a base class to handle the shared logic and separate subclasses each with their own *separate* lists of "all names" and signals for when names are added. (Or... something else. Having a token specify the "category" of name might also be a possibility, but seems like it would be more effort. There may also be alternatives that aren't occurring to me offhand.)

**Comment by dstoup** [comment]
@tao558 @johnwparent  .. in case you guys didn't see this one.

**Comment by tao558** [comment]
Would making the class templated over the various types work? Like having class_map<detected_object>, or class_map<activity>? @mwoehlke-kitware

**Comment by linus-sherrill** [comment]
I think the problem is in the global pool of labels. Each variant of class_map needs its own separate pool. You could have a base class that provides the common methods and the derived class would provide the class static label pool. This would not be a polymorphic application, although you could have a virtual method to return the address of the label pool or address of a label. We would go back to having a `detected_object_type` and `activity_type` classes that would share a base class.

**Comment by mwoehlke-kitware** [comment]
@tao558, what Linus said. More specifically, the problem is the static members `class_name_added` and `s_master_name_set` (and by extension, `s_table_mutex`). These need to be different for each "flavor".

For performance reasons, it's probably best to avoid a virtual method. Something with templates may be possible *provided* they are exported and explicitly instantiated.

The API for the signal may need to change from a public member to an accessor that returns a reference/pointer, but that should be fine.

**Comment by collinsr** [comment]
On Wed, Aug 12, 2020 at 9:35 AM Matthew Woehlke <notifications@github.com>
wrote:

> For performance reasons, it's probably best to avoid a virtual method.
>

Have we ever measured the impact of this sort of thing across an
application? (Just curious, I fully realize I'm jumping in the middle here
without full context.)

**Comment by mwoehlke-kitware** [comment]
> Have we ever measured the impact of this sort of thing across an application?

It's probably negligible, but I'd classifiy it as near to premature pessimization, i.e. not hard to avoid, so why do it?
