### ISSUE TITLE
[Flatpak] Please allow using system installed Pybind11 or cmake flag to find it.

### ISSUE THREAD

**Issue by kevinsmia1939** [Kitware/kwiver#1245]
Hello,

I have been trying to Flatpak Telesculptor.
https://github.com/Kitware/TeleSculptor/issues/425

Flatpak is a packaging and distributing desktop software on Linux.
https://www.flatpak.org/

I would like it to be submit to Flathub, an app store for Flatpak apps. Many Linux distros supported Flatpak. So I think it would be beneficial to package large software like Telesculptor into Flatpak.
https://flathub.org/home

This is the Flatpak manifest that I have been working on so far.
https://github.com/Kitware/TeleSculptor/pull/428

Since Flathub does not allow external downloads while building, attemps to download while building will fail, Flathub cite the reason to be reproducible build. So I have included many dependencies that would have been downloaded by Fletch. 

At first the error is `pybind11config.cmake` is missing, but using the cmake flag `-Dpybind11_DIR` solve the issue. (see the cmake flags below)
Right now Kwiver does not build due to the error below.

```
[ 10%] Building CXX object python/kwiver/sprokit/util/CMakeFiles/sprokit_python_util.dir/pystream.cxx.o
In file included from /run/build/kwiver/python/kwiver/sprokit/util/pystream.cxx:5:
/run/build/kwiver/python/kwiver/sprokit/util/pystream.h:12:10: fatal error: pybind11/pybind11.h: No such file or directory
   12 | #include <pybind11/pybind11.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [python/kwiver/sprokit/util/CMakeFiles/sprokit_python_util.dir/build.make:82: python/kwiver/sprokit/util/CMakeFiles/sprokit_python_util.dir/pystream.cxx.o] Error 1
```
It ask for Pybind11 which I have already install in Flatpak manifest file.
I am not aware of cmake flag that point to correct pybind11.h directory, does that flag exist?

I suspect that the reason it cannot find Pybind11 is because it use `#include <pybind11/pybind11.h>` instead of `find_package(pybind11)`, from what I understand, `#include` does not aware of system install package, so `find_package` is recommended as stated in this doc, https://pybind11.readthedocs.io/en/stable/compiling.html#find-package-vs-add-subdirectory.

So I would like to have cmake flag that point to system installed Pybind11 or add ability to detect system installed Pybind11.

These are the cmake flags I use to build kwiver.

```
      - -DBUILD_SHARED_LIBS:BOOL=ON
      - -DKWIVER_ENABLE_ARROWS:BOOL=ON
      - -DKWIVER_ENABLE_BURNOUT:BOOL=OFF
      - -DKWIVER_ENABLE_CERES:BOOL=ON
      - -DKWIVER_ENABLE_CUDA:BOOL=OFF
      - -DKWIVER_ENABLE_C_BINDINGS:BOOL=ON
      - -DKWIVER_ENABLE_PYTHON:BOOL=ON
      - -DKWIVER_ENABLE_DARKNET:BOOL=OFF
      - -DKWIVER_ENABLE_DLL_WARNINGS:BOOL=OFF
      - -DKWIVER_ENABLE_DOCS:BOOL=OFF
      - -DKWIVER_ENABLE_EXAMPLES:BOOL=OFF
      - -DKWIVER_ENABLE_EXTRAS:BOOL=ON
      - -DKWIVER_ENABLE_FFMPEG:BOOL=ON
      - -DKWIVER_ENABLE_KPF:BOOL=OFF
      - -DKWIVER_ENABLE_GDAL:BOOL=ON
      - -DKWIVER_ENABLE_LOG4CPLUS:BOOL=ON
      - -DKWIVER_ENABLE_LOG4CXX:BOOL=OFF
      - -DKWIVER_ENABLE_MATLAB:BOOL=OFF
      - -DKWIVER_ENABLE_MVG:BOOL=ON
      - -DKWIVER_ENABLE_OPENCV:BOOL=ON
      - -DKWIVER_ENABLE_OPENMP:BOOL=ON
      - -DKWIVER_ENABLE_PROCESSES:BOOL=ON
      - -DKWIVER_ENABLE_PROJ:BOOL=ON
      - -DKWIVER_ENABLE_PYTHON:BOOL=ON
      - -DKWIVER_ENABLE_QT:BOOL=ON
      - -DKWIVER_ENABLE_QT_EXT:BOOL=ON
      - -DKWIVER_ENABLE_RightTrack:BOOL=OFF
      - -DKWIVER_ENABLE_SPROKIT:BOOL=ON
      - -DKWIVER_ENABLE_SUPER3D:BOOL=ON
      - -DKWIVER_ENABLE_TESTS:BOOL=OFF
      - -DKWIVER_ENABLE_TOOLS:BOOL=ON
      - -DKWIVER_ENABLE_TRACK_ORACLE:BOOL=OFF
      - -DKWIVER_ENABLE_UUID:BOOL=OFF
      - -DKWIVER_ENABLE_VISCL:BOOL=OFF
      - -DKWIVER_ENABLE_VXL:BOOL=ON
      - -DKWIVER_INSTALL_SET_UP_SCRIPT:BOOL=ON
      - -DKWIVER_TEST_ADD_TARGETS:BOOL=OFF
      - -DKWIVER_USE_BUILD_TREE:BOOL=OFF
      - -DKWIVER_USE_CONFIGURATION_SUBDIRECTORY:BOOL=OFF
      - -DCMAKE_BUILD_TYPE:STRING=Release
      - -DCMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=ON
      - -DPYTHON_VERSION_MAJOR:STRING=3
      - -DPROJ_INCLUDE_DIR:PATH=/app/include/proj
      - -DPROJ_LIBRARY:PATH=/app/lib
      - -Dpybind11_DIR:PATH=/app/lib/python3.8/site-packages/pybind11-2.6.2-py3.8.egg/pybind11/share/cmake/pybind11
```

Kind regards,
Kevin

**Comment by mleotta** [comment]
@kevinsmia1939 Thank you again for your contributions here.  This is great.

One issue you might be encountering is that Fletch does more than just build all of those source packages, it also applies patches when needed to fix issues in these versions of packages.  I think we may have patches for pybind11.  I think your best bet is still to build using Fletch.  However, there might be another solution to the Flatpak download issue.  Could you use the Flatpak manifest to download the packages the Fletch needs, but not build them?  If you put all the tarballs or zips that Fletch needs into the `fletch/Downloads` directory then fletch will used them without trying to download (as long as the checksums match).  So what I suggest is that you list all the packages that Fletch needs in the Flatpak file but the "build" step for these packages would be to just move the downloaded files into `fletch/Downloads`.  And then you can build with fletch.  You could even do this with the TeleSculptor superbuild.  You would just need to put the files in `TeleSculptor/external/fletch/Downloads`.  Do you think Flatpak would support this?

**Comment by kevinsmia1939** [comment]
> @kevinsmia1939 Thank you again for your contributions here. This is great.
> 
> One issue you might be encountering is that Fletch does more than just build all of those source packages, it also applies patches when needed to fix issues in these versions of packages. I think we may have patches for pybind11. I think your best bet is still to build using Fletch. However, there might be another solution to the Flatpak download issue. Could you use the Flatpak manifest to download the packages the Fletch needs, but not build them? If you put all the tarballs or zips that Fletch needs into the `fletch/Downloads` directory then fletch will used them without trying to download (as long as the checksums match). So what I suggest is that you list all the packages that Fletch needs in the Flatpak file but the "build" step for these packages would be to just move the downloaded files into `fletch/Downloads`. And then you can build with fletch. You could even do this with the TeleSculptor superbuild. You would just need to put the files in `TeleSculptor/external/fletch/Downloads`. Do you think Flatpak would support this?

For Telesculptor superbuild, I have to create new folder called external/fletch/Downloads inside TeleSculptor?

**Comment by kevinsmia1939** [comment]
@mleotta 

Hello,

I manage to download the fletch archive with commit specify in telesculptor-external-fletch.cmake into telesculptor external/fletch/Downloads directory. But Telesculptor does not seems to see the archive. Must it be unpack first?

**Comment by russelldj** [comment]
@kevinsmia1939 I'm not as familiar with the superbuild as @mleotta but in my configuration I have an empty `<build_dir>/external/fletch` folder. I'm not 100% sure on what you're doing, but if fletch is getting pulled into the superbuild, that folder should exist in the build tree. Then you can just move the files to that folder.

**Comment by kevinsmia1939** [comment]
> @kevinsmia1939 I'm not as familiar with the superbuild as @mleotta but in my configuration I have an empty `<build_dir>/external/fletch` folder. I'm not 100% sure on what you're doing, but if fletch is getting pulled into the superbuild, that folder should exist in the build tree. Then you can just move the files to that folder.

I attempt to package Telesculptor binary into Flatpak format that most linux distro and desktop environment support though their software store. If successful, Telesculptor can be easily install from those software store. The issue right now is that Flathub (Flatpak collection store) does not allow network connection while building, so I am trying to pre-download everything needed by Fletch, but I'm not sure where and what format it prefer.

**Comment by russelldj** [comment]
I think you can consult [this file](https://github.com/Kitware/fletch/blob/master/CMake/fletch-tarballs.cmake) for a list of data files needed by fletch. If you choose to build fletch locally as a stand-alone project, it should populate the `<src dir>/Downloads` file with all of these files. Thanks again for your work on this, it sounds really exciting!

**Comment by russelldj** [comment]
For reference, here are the files that are downloaded by my relatively-current version of `fletch` 
```
boost_1_65_1.tar.bz2           openblas-0.3.10.tar.gz
caffe-fletch-linux.zip         opencv-3.4.0.zip
caffe-segnet-abcf30d.zip       opencv-contrib-3.4.0.zip
ceres-solver-1.14.0.tar.gz     openjpeg-v2.3.0.tar.gz
cppdb-0.3.0.tar.bz2            PDAL-1.7.2-src.tar.gz
cppzmq-v4.2.3.zip              postgis-2.5.3.tar.gz
darknent-d206b6da7af1f4.zip    postgresql-9.5.1.tar.bz2
eigen-3.3.7.tar.gz             proj-4.9.3.tar.gz
ffmpeg-3.3.3.tar.gz            protobuf-cpp-3.4.1.tar.gz
gdal-2.3.2.tar.gz              pybind11-2.2.1.tar.gz
GeographicLib-1.49.tar.gz      pybind11-2.5.0.tar.gz
geos-3.6.2.tar.bz2             qt-everywhere-src-5.11.2.tar.xz
gflags-2.2.1.tar.gz            qtExtensions-20200330gitb2848e06.tar.gz
glog-0.3.5.tar.gz              shapelib-1.4.1.tar.gz
gtest-1.8.1.tar.gz             snappy-1.1.3.tar.gz
hdf5-1_12_0.tar.gz             SuiteSparse-4.4.5.tar.gz
hdf5-1.8.17.tar                tiff-4.1.0.tar.gz
leveldb-1.19.tar.gz            tinyXML1.zip
libgeotiff-1.4.2.zip           tinyXML2.zip
libjpeg-turbo-1.4.0.tar.gz     v1.3.0.tar.gz
libjson_7.6.1.zip              VTK-8.2.0.tar.gz
libkml-20150911git79b3eb0.zip  VTK-8.2.0.zip
libpng-1.6.19.tar.gz           vxl-0bb0ca92867408caec298cef05412ed85c6d56b7.zip
libxml2-2.9.0.tar.gz           yaml-cpp-release-0.5.3.tar.gz
LMDB_0.9.16.tar.gz             ZeroMQ-v4.2.5.tar.gz
log4cplus-2.0.x.zip            zlib-1.2.11.zip
```

**Comment by kevinsmia1939** [comment]
@russelldj 
That is very helpful, thank so much.
If you are interest, i did successfully Flatpak Paraview and Tomviz.
3D slicer have same problem as Telesculptor due to Fletch as well.

https://discourse.paraview.org/t/i-flatpak-paraview-any-thought/6698
https://github.com/OpenChemistry/tomviz/issues/2157
https://discourse.slicer.org/t/interest-to-create-flatpak-for-3d-slicer-have-issue-with-guisupportqtopengl-not-found/16532

But Paraview no respond so far, no one see or interest? :(

**Comment by russelldj** [comment]
Very cool. I'm not involved with those projects but I may check your Flatpack builds out. 

I'm certainly happy to help to keep this moving forward. I'm rebuilding fletch and can send you the updated list once that's done.

**Comment by kevinsmia1939** [comment]
I will close this since it is not relevant here anymore.
I will have to wait until TeleSculptor migrate to VTK 9 because VTK 8 failed to build on newer cmake.
