### ISSUE TITLE
"no such process of type 'convert_image'" error despite registered implementation

### ISSUE THREAD

**Issue by russelldj** [Kitware/kwiver#1279]
I was trying to add the `bypass` implementation of `convert_image` to my pipeline. When I ran it, I got the following error: 
```Caught unhandled kwiver::vital::vital_exception: There is no such process of type 'convert_image' in the registry, thrown from /home/local/KHQ/david.russell/dev/KWIVER/new-source/sprokit/src/sprokit/pipeline/process_factory.cxx:125```
The odd part is when I ran `plugin_explorer --all` it lists 
```
Info on algorithm type "convert_image" implementation "bypass"
  Plugin name: bypass
      Performs no conversion and returns the given image container.
```
However, there's no `Process type: convert_image` block as there are for many other processes. I'm a bit lost on where the issue is.

**Comment by linus-sherrill** [comment]
I checked and I could not find any process that wraps the `convert_image` algorithm type. I also did not find any other implementations (other than a disused one in viscl). This algorithm type only converts the format of an image (and is apparently not used much) (e.g. from vital image format to OCV format). Is that what you want to do?

**Comment by russelldj** [comment]
In #1275 we are discussing how to structure included superprocess-like include-able pipelines. @mwoehlke-kitware requested using a dummy input process to facilitate consistent naming. That was the goal of using this process, since my understanding was it simply returned the input.

**Comment by linus-sherrill** [comment]
Now I see what you were doing. Do do that you would need to write  a new process that wraps that algo type. I don't know that much about your pipeline environment, but would clusters work?

**Comment by russelldj** [comment]
I'm confused on your first point. I thought that the [bypass convert image implementation](https://github.com/Kitware/kwiver/blob/master/arrows/core/convert_image_bypass.cxx) was already a process. More broadly, I thought that all arrow implementations were processes. Is the change you are suggesting something that needs to happen at the arrow level or the vital level?

There's been a lot of back and forth about the value of clusters in that PR and elsewhere, such as the most recent KWIVER working group. I think the consensus is they would work in this situation, we're just not sure they're valuable enough to deal with the additional complexity and the inability to access internal intermediate values. I think @mwoehlke-kitware can probably give a better summary but it seems like there's a few frustrating quirks, such as using different include paths.

**Comment by russelldj** [comment]
To the first point, I'm guessing you were talking about `sprokit/processes`? That was a mechanism I was previously unaware of, but seems to make more sense now.

**Comment by mwoehlke-kitware** [comment]
BTW, IIRC when I needed a dummy process, I used `vxl_convert_image` (which is an `image_filter`).

Also BTW, you may want the dummy to be the *output* rather than the input, since inpainting needs two inputs, and I'm not sure we have a good way to pass those through. (Although this seems like something we should maybe fix...)

**Comment by mwoehlke-kitware** [comment]
@linus-sherrill, you missed the summit earlier this week where we were talking about clusters vs. including `.pipe` files. One of the issues (besides that IIRC they are a bit finicky to set up) is that clusters use some totally different mechanism for how to find them, whereas we are using the `config_block_io` logic for configs, pipes, and other data files (i.e. "everything *but* clusters"). At some point I think there needs to be follow-up on that conversation, which we probably shouldn't try to do in GitHub comments 🙂.
