### ISSUE TITLE
Python package automatically registers a python debug logger

### ISSUE THREAD

**Issue by Purg** [Kitware/kwiver#1361]
Using a `pip install kwiver` installation (v1.4.6).

When starting an interpreter and invoking `import kwiver.vital` causes a `logging.Logger` to be *globally* registered such that any module with debug logging inside starts emitting. This is most obviously seen when running ipython as it's use of the parso package starts emitting debug logging upon attempting tab completion:
![image](https://user-images.githubusercontent.com/735270/124026006-25bc2400-d9bf-11eb-83d8-af5294c9eaf7.png)
(NOTE: the DEBUG output from parso)

This is definitely on the python side of things otherwise parso would not output as well as we can see the hander added:
![image](https://user-images.githubusercontent.com/735270/124026317-86e3f780-d9bf-11eb-9256-47fee2a3b8c8.png)
NOTE:
* Empty global handlers list before `import kwiver.vital` and it's population *after* the import.
* Effect of debug logging seen for `In [6]` and `In [7]`, but *NOT* `In [9]` after manual removal.

**Comment by Purg** [comment]
@as6520 @dstoup @johnwparent

**Comment by as6520** [comment]
I think I had started addressing it in https://github.com/Kitware/kwiver/pull/963. Let me rebase it on master and address this problem. Sorry for the delay in fixing this problem
