### ISSUE TITLE
Building tests requires sourcing `setup_KWIVER.sh`

### ISSUE THREAD

**Issue by russelldj** [Kitware/kwiver#1370]
This is something I've hit a number of times and find relatively annoying. If I try to build KWIVER with tests, I get a strange gtest linking error if I don't source `setup_KWIVER.sh` in the build tree. 

My config is Ubuntu 18.04, `g++7.5.0`, and the `zsh` shell. If I end up hitting the issue again I'll post the error.

**Comment by borovik135** [comment]
Confirming the case, I also see some strange link errors on Ubuntu 20.04 LTS when building kwiver with tests. The errors magically disappear when I source setup_KWIVER.sh

**Comment by russelldj** [comment]
I know @dstoup suggested this as a solution, so perhaps he has insight into why it's occurring. I haven't touched this in a while so I don't remember a ton, it was just a backlog task.
