### ISSUE TITLE
KWIVER consumers can't build against an install. Variant.hpp publicly exposed

### ISSUE THREAD

**Issue by dstoup** [Kitware/kwiver#1521]
Back in November a PR landed that has variant.hpp included in the header, visit.h. Visit.h is installed but variant.hpp is not which prevents any external build from succeeding against an installed KWIVER. We either need to remove variant.hpp from 'internal' or fix visit so variant.hpp is kept internal.

**Comment by daniel-riehm** [comment]
Tentatively closing as issue seems to have been resolved by #1522
