### ISSUE TITLE
Vital mesh crashes on some face configurations

### ISSUE THREAD

**Issue by willdunklin** [Kitware/kwiver#1633]
Consider the creation of the following mesh consisting of four vertices and two faces:
```c++
auto verts = new kv::mesh_vertex_array<3>;
auto faces = new kv::mesh_regular_face_array<3>;

verts->push_back({0, 0, 0}); // vertex 0
verts->push_back({0, 0, 1}); // vertex 1
verts->push_back({1, 0, 1}); // vertex 2
verts->push_back({0, 1, 1}); // vertex 3

faces->push_back({0, 1, 2}); // face 0
faces->push_back({0, 1, 3}); // face 1

kv::mesh_sptr mesh = std::make_shared<kv::mesh>(
  std::unique_ptr<kv::mesh_vertex_array_base>(verts),
  std::unique_ptr<kv::mesh_face_array_base>(faces));
```
(which roughly corresponds to this visualization)
![mesh](https://user-images.githubusercontent.com/54944980/174664452-411623b8-b650-4732-a000-2ae3d2656028.png)

This seems like it should be a legal mesh, however, due to the way we specified the two faces the code will exit when [building the graph's edges](https://github.com/Kitware/kwiver/blob/master/vital/types/mesh.cxx#L742-L759):
```c++
mesh->build_edge_graph();
```

---------------------------------------
What breaks is [this assertion](https://github.com/Kitware/kwiver/blob/master/vital/types/mesh.cxx#L438) (see below), which seems to check if any ordered vertex pair is reused when constructing any face in the mesh. 

For example, in the above mesh the first face is made of the ordered vertex pairs `0,1`, `1,2` and `2,0`. Since the second pair also uses `0,1`, the assertion below halts execution.
**(Note: if the second face had the pair `1,0` instead of `0,1`, the assertion would *not* halt)**

```c++
assert( half_edges_[ curr_e ].vert_index() == v );
```
---------------------------------------

This requirement on face specification seems to be highly limiting and most likely unintentional. I don't have a complete understanding of how `half_edges_` is used within the `mesh` class though, so this might have necessary importance in those algorithms.

Does anyone know if such behavior is intended?

**Comment by mleotta** [comment]
This failure mode is intended.  Whether it should fail more gracefully is an open question, but this case should fail.  Meshes are required to be manifolds with consistently oriented faces.  The direction of normal vector is defined by a right hand rule traversal of a faces edges.  Adjacent faces should have consistent normals.  Each edge should be traversed at most once I'm each direction.  You can represent non manifold meshes by lists of faces, but those are considered "broken" meshes.  In some cases, like this one, you could algorithmically detect and reverse inconsistent faces, but there are other cases, like 3 faces sharing an edge, that can't be fixed.

**Comment by willdunklin** [comment]
Thanks for the clarification, I'll look into adding a more graceful/informational exception for this case.
