### ISSUE TITLE
thread_pool test hangs when listing tests

### ISSUE THREAD

**Issue by mwoehlke-kitware** [Kitware/kwiver#407]
On Windows (particularly, on our current CI machine; may not affect all Windows machines), the `thread_pool` test is mysteriously hanging during test discovery (i.e. if run with `--gtest_list_tests`). Strangely, it does not hang if run with no arguments (i.e. in "run all tests" mode).

It seems to be stuck in `~unique_ptr` for a `thread_pool` related object. I would guess there is an issue with some static initialization, particularly in the case that the thread pool is initialized but not used.

Note that the test calls `thread_pool::instance().available_backends()` in the static initializer to set up the paramaterized tests.

This is an issue because it leads to a build failure. (Prior to #406, it would cause the build to hang.)

**Comment by mwoehlke-kitware** [comment]
I've managed to obtain a reasonable stack trace from a debug build. It is hanging at `condition.notify_all();` in the `thread_pool_builtin_backend` destructor. Here is the full stack trace:

```
vital_util.dll!std::condition_variable::notify_all() Line 561
vital_util.dll!kwiver::vital::thread_pool_builtin_backend::~thread_pool_builtin_backend() Line 79
[External Code]
vital_util.dll!std::default_delete<kwiver::vital::thread_pool::backend>::operator()(kwiver::vital::thread_pool::backend * _Ptr) Line 1608
vital_util.dll!std::unique_ptr<kwiver::vital::thread_pool::backend,std::default_delete<kwiver::vital::thread_pool::backend> >::~unique_ptr<kwiver::vital::thread_pool::backend,std::default_delete<kwiver::vital::thread_pool::backend> >() Line 1820
[External Code]
vital_util.dll!std::default_delete<kwiver::vital::thread_pool::priv>::operator()(kwiver::vital::thread_pool::priv * _Ptr) Line 1608
vital_util.dll!std::unique_ptr<kwiver::vital::thread_pool::priv,std::default_delete<kwiver::vital::thread_pool::priv> >::~unique_ptr<kwiver::vital::thread_pool::priv,std::default_delete<kwiver::vital::thread_pool::priv> >() Line 1820
vital_util.dll!kwiver::vital::thread_pool::~thread_pool() Line 152
```

**Comment by mwoehlke-kitware** [comment]
This code seems sufficient to cause the hang:

```c++
#include <vital/util/thread_pool.h>
auto bad = kwiver::vital::thread_pool::instance().available_backends();
int main() { return 0; }
```

**Comment by mleotta** [comment]
Note: this is a duplicate of #208

**Comment by mwoehlke-kitware** [comment]
(Closing as duplicate)
