### ISSUE TITLE
How to register new processes to Sprokit?

### ISSUE THREAD

**Issue by tpinkowski** [Kitware/kwiver#5]
I'm not sure to which repository I should post my question.
because I saw Sprokit also in the dev branch here:
https://github.com/Kitware/kwiver/tree/dev/add-track-oracle/sprokit

So the original question/issue is here:
https://github.com/Kitware/sprokit/issues/8

**Comment by mleotta** [comment]
I'm not the best person to answer you question, but I may be able to provide some insight into why Sprokit is in two places.  We are in the process of refactoring KWIVER.  Previously KWIVER was a "super build".  That is, it was light weight wrapper project designed to pull in and build together various other open source projects that fall under the KWIVER family of tools.  The new KWIVER layout will unify three core projects into one repository: Vital, Sprokit, and Arrows.  The separate repositories for these projects will eventually go away.

Vital provides support for configuration file management, logging, core data structures, and abstract algorithm APIs.  Arrows provides a collection of plugins that implements those APIs, often using external projects (OpenCV, VXL, Caffe, etc.).  Sprokit provides the stream processing architecture for combining those components together into a pipeline for process video or other streaming data.

The transition from KWIVER as a "super build" to KWIVER as a stand alone project is in progress but has not landed in the master branch yet.  We expect to complete this over the next month.  Other projects that previously used Vital and Sprokit directly will be transitioned to use the new KWIVER. Arrows is a subset of the MAP-Tk project which is being ripped out and relocated into KWIVER.
