### ISSUE TITLE
OpenCV compatibility

### ISSUE THREAD

**Issue by skn123** [Kitware/kwiver#544]
``
/home/naths/srcs/kwiver/arrows/ocv/estimate_fundamental_matrix.cxx:152:39: error: 
      use of undeclared identifier 'CV_FM_RANSAC'; did you mean 'cv::FM_RANSAC'?
                                      CV_FM_RANSAC,
                                      ^~~~~~~~~~~~
                                      cv::FM_RANSAC
/usr/local/include/opencv2/calib3d.hpp:286:8: note: 'cv::FM_RANSAC' declared
      here
       FM_RANSAC = 8  //!< RANSAC algorithm. It needs at least 15 points...
       ^
[ 88%] Built target processes_clusters
/home/naths/srcs/kwiver/arrows/ceres/options.cxx:70:52: error: no member named
      'num_linear_solver_threads' in 'ceres::Solver::Options'
  config->set_value("num_linear_solver_threads", o.num_linear_solver_threads,
                                                 ~ ^
/home/naths/srcs/kwiver/arrows/ceres/options.cxx:107:21: error: no member named
      'num_linear_solver_threads' in 'ceres::Solver::Options'
  GET_VALUE(int,    num_linear_solver_threads);
  ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/naths/srcs/kwiver/arrows/ceres/options.cxx:104:11: note: expanded from
      macro 'GET_VALUE'
  options.vname = config->get_value< vtype >(#vname, options.vname);
  ~~~~~~~ ^
/home/naths/srcs/kwiver/arrows/ceres/options.cxx:107:21: error: no member named
      'num_linear_solver_threads' in 'ceres::Solver::Options'
  GET_VALUE(int,    num_linear_solver_threads);
  ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/naths/srcs/kwiver/arrows/ceres/options.cxx:104:62: note: expanded from
      macro 'GET_VALUE'
  options.vname = config->get_value< vtype >(#vname, options.vname);
                                                     ~~~~~~~ ^
1 error generated.
arrows/ocv/CMakeFiles/kwiver_algo_ocv.dir/build.make:231: recipe for target 'arrows/ocv/CMakeFiles/kwiver_algo_ocv.dir/estimate_fundamental_matrix.cxx.o' failed
make[2]: *** [arrows/ocv/CMakeFiles/kwiver_algo_ocv.dir/estimate_fundamental_matrix.cxx.o] Error 1
/home/naths/srcs/kwiver/arrows/ocv/draw_detected_object_set.cxx:197:84: error: 
      use of undeclared identifier 'CV_FILLED'
  ...cv::Point( text.width, -text.height ), cv::Scalar( 0, 0, 0 ), CV_FILLED );
                                                                   ^
1 error generated.
arrows/ocv/CMakeFiles/kwiver_algo_ocv.dir/build.make:205: recipe for target 'arrows/ocv/CMakeFiles/kwiver_algo_ocv.dir/draw_detected_object_set.cxx.o' failed
make[2]: *** [arrows/ocv/CMakeFiles/kwiver_algo_ocv.dir/draw_detected_object_set.cxx.o] Error 1
/home/naths/srcs/kwiver/arrows/ocv/hough_circle_detector.cxx:164:32: error: no
      member named 'BGR2GRAY' in namespace 'cv'
  cvtColor( src, src_gray, cv::BGR2GRAY );
                           ~~~~^
/home/naths/srcs/kwiver/arrows/ocv/hough_circle_detector.cxx:174:21: error: use
      of undeclared identifier 'CV_HOUGH_GRADIENT'; did you mean
      'cv::HOUGH_GRADIENT'?
                    CV_HOUGH_GRADIENT, // i: method
                    ^~~~~~~~~~~~~~~~~
                    cv::HOUGH_GRADIENT
>

**Comment by dstoup** [comment]
What version of OpenCV are you using?
It looks like a system installed version of OpenCV, correct?
What operating system are you running this on, Linux distro, version, etc?

**Comment by skn123** [comment]
I dont use any system installed versions :)
Ubuntu 17.10
OpenCV - Fresh checkout from master and built with ceres enabled
Ceres - Fresh checkout from master

**Comment by dstoup** [comment]
Ok, I was confused by the location of OpenCV headers in /usr/local/include

FWIW, building from OpenCV master is untested. I recommend checking out  https://github.com/Kitware/fletch.git and building the OpenCV/Ceres from it. If you don't want to do that, you can use the supported versions from it:

OpenCV: 3.4.0
Ceres:  1.13.0

Some deviation will likely work but just using masters is not recommended.

If you still have issues building with those packages, please report back.

**Comment by Cookt2** [comment]
This appears to have been resolved. Feel free to re-open if issue persists with the same details. Closing issue...
