### ISSUE TITLE
explorer_plugin_export.h missing

### ISSUE THREAD

**Issue by mattbrown11** [Kitware/kwiver#69]
When I try to build, I get 
.../kwiver/vital/algo/algo_explorer_plugin.cxx:31:48: fatal error: vital/tools/explorer_plugin_export.h: No such file or directory
 #include <vital/tools/explorer_plugin_export.h>

**Comment by linus-sherrill** [comment]
The problem was in building the explorer plugins when the KWIVER_ENABLE_TOOLS option was not enabled. Now these plugins are not built if the tools are not enabled.
