### ISSUE TITLE
X11_Xt_LIB could not be found

### ISSUE THREAD

**Issue by mattbrown11** [Kitware/kwiver#73]
CMake Error at Rendering/OpenGL/CMakeLists.txt:346 (message):
  X11_Xt_LIB could not be found.  Required for VTK X lib.

make[2]: *** [build/src/VTK-stamp/VTK-configure] Error 1
make[1]: *** [CMakeFiles/VTK.dir/all] Error 2

I installed libxt-dev to overcome.

**Comment by linus-sherrill** [comment]
This is more of a VTK problem than a KWIVER problem.
