### ISSUE TITLE
Log4cxx_INCLUDE_DIR missing

### ISSUE THREAD

**Issue by mattbrown11** [Kitware/kwiver#74]
During the KWIVER build, I get
CMake Error at /opt/cmake/cmake-3.8.0-rc1-Linux-x86_64/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:137
 (message):
   Log4cxx_INCLUDE_DIR (missing: Log4cxx_LIBRARY)
 Call Stack (most recent call first):
   /opt/cmake/cmake-3.8.0-rc1-Linux-x86_64/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:377
 (_FPHSA_FAILURE_MESSAGE)
   CMake/FindLog4cxx.cmake:24 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
   CMake/kwiver-depends-log4cxx.cmake:11 (find_package)
   CMake/kwiver-depends.cmake:8 (include)
   CMakeLists.txt:104 (include)

installed liblog4cxx10-dev to overcome it.

**Comment by linus-sherrill** [comment]
Log4cxx is provided by fletch, as is log4cplus but they need to be enabled when building fletch.

**Comment by dstoup** [comment]
FYI, Log4cxx is not in fletch. We never moved it over because of the preference for log4CPlus.
