### ISSUE TITLE
kwiver_setup_msvc_env doesn't handle variable redefinition

### ISSUE THREAD

**Issue by mleotta** [Kitware/kwiver#740]
The logic in `kwiver_setup_msvc_env` does not support redefining an environment variable.  It assumes any time a variable is set more than once it is to append (e.g. `set PATH=C:\another\path;%PATH%`).  However, we may also want to redefine a variable.  This is needed for projects to override settings in `setup_KWIVER.bat`.  For example, I may want my project to override `LOG4CPLUS_CONFIGURATION` with the path to my Log4cplus config file, not use the KWIVER default.  Let's say I have `setup_MyProject.bat` that calls `setup_KWIVER.bat` and then redefines `LOG4CPLUS_CONFIGURATION`.  

```
call setup_KWIVER.bat
set LOG4CPLUS_CONFIGURATION=C:/Build/MyProject/log4cplus.properties
```

This works in the batch files, but the `kwiver_setup_msvc_env` appends instead, and I get the following in my MSVC environment:

```
LOG4CPLUS_CONFIGURATION=C:/Build/kwiver/log4cplus.properties;C:/Build/MyProject/log4cplus.properties;
```
what I should get instead is
```
LOG4CPLUS_CONFIGURATION=C:/Build/MyProject/log4cplus.properties;
```

**Comment by aaron-bray** [comment]
is this OBE by issue 741?

**Comment by mleotta** [comment]
Yes this is resolved now.
