### ISSUE TITLE
Add image_container::get_image(x_offset, y_offset, width, height)

### ISSUE THREAD

**Issue by mleotta** [Kitware/kwiver#760]
To support efficiently loading small crops of very large images we should add the method:
```c++
kwiver::vital::image_container::get_image(unsigned x_offset, unsigned y_offset,
                                          unsigned width, unsigned height);
```
For basic image containers that store images in memory, this method should just return a cropped view into the full image.  However, for containers that load from disk on demand (e.g. the GDAL container) this would allow them to only load the pixel that they need.  This is important for processing very large images, like satellite images, where you only need to load a small area of interest.

**Comment by chetnieter** [comment]
Address in #767
